
// WorkspaceActions
export const TOGGLE_TOOLSFRAME = 'TOGGLE_TOOLSFRAME';

// PreferencesActions
export const SET_THEME = 'SET_THEME';

// USERActions
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER';
// export const SET_PREFERENCES = 'SET_PREFERENCES';
export const VERIFY_SIGNUP_INITIATE = 'VERIFY_SIGNUP_INITIATE';
export const VERIFY_SIGNUP_SUCCESSFUL = 'VERIFY_SIGNUP_SUCCESSFUL';
export const VERIFY_SIGNUP_FAILED = 'VERIFY_SIGNUP_FAILED';
export const PASSWORD_RESET_INITIATE = 'PASSWORD_RESET_INITIATE';
export const RESET_PASSWORD_RESET_INITIATE = 'RESET_PASSWORD_RESET_INITIATE';

// ProjectActions
export const START_NEW_NETWORK_SCHEMA = 'START_NEW_NETWORK_SCHEMA';
export const SET_NETWORK_TYPE = 'SET_NETWORK_TYPE';
export const SET_NETWORK_OP_MODE = 'SET_NETWORK_OP_MODE';
export const SET_NETWORK_OPTIMIZER = 'SET_NETWORK_OPTIMIZER';
export const SET_NETWORK_USE_LR = 'SET_NETWORK_USE_LR';
export const SET_NETWORK_LR = 'SET_NETWORK_LR';
export const SET_NETWORK_MOMENTUM = 'SET_NETWORK_MOMENTUM';
export const SET_NETWORK_USE_NESTEROV = 'SET_NETWORK_USE_NESTEROV';
export const SET_NETWORK_INITIAL_ACCUMULATOR_VALUE = 'SET_NETWORK_INITIAL_ACCUMULATOR_VALUE';
export const SET_NETWORK_RHO = 'SET_NETWORK_RHO';
export const SET_NETWORK_EPSILON = 'SET_NETWORK_EPSILON';
export const SET_NETWORK_BETA1 = 'SET_NETWORK_BETA1';
export const SET_NETWORK_BETA2 = 'SET_NETWORK_BETA2';
export const SET_NETWORK_DECAY = 'SET_NETWORK_DECAY';
export const SET_NETWORK_CENTERED = 'SET_NETWORK_CENTERED';
export const SET_NETWORK_LOSS = 'SET_NETWORK_LOSS';
export const SET_LAST_COMPILED = 'SET_LAST_COMPILED';
export const SET_PROJECT_CURRENT_FILE = 'SET_PROJECT_CURRENT_FILE';
export const SET_PROJECT_FILES = 'SET_PROJECT_FILES';
export const OPEN_PROJECT_SUCCESSFUL = 'OPEN_PROJECT_SUCCESSFUL';
export const OPEN_PROJECT_FAILED = 'OPEN_PROJECT_FAILED';
export const RESET_PROJECT = 'RESET_PROJECT';
export const POST_LAYER_TO_TAIL = 'POST_LAYER_TO_TAIL';
export const POST_LAYER_TO_INDEX = 'POST_LAYER_TO_INDEX';
export const REMOVE_LAYER = 'REMOVE_LAYER';
export const MOVE_LAYER_TO_INDEX = 'MOVE_LAYER_TO_INDEX';
export const UPDATE_ALL_LAYER_OPTIONS = 'UPDATE_ALL_LAYER_OPTIONS';
export const START_NEW_TF_MODEL = 'START_NEW_TF_MODEL';
export const SET_PROJECT_SAVE_INITIATED = 'SET_PROJECT_SAVE_INITIATED';
export const SET_PROJECT_SAVE_SUCCESSFUL = 'SET_PROJECT_SAVE_SUCCESSFUL';
export const RESET_PROJECT_SAVE_SUCCESSFUL = 'RESET_PROJECT_SAVE_SUCCESSFUL';
export const SET_PROJECT_SAVE_FAILED = 'SET_PROJECT_SAVE_FAILED';
export const SET_PROJECT_SAVE_AS_INITIATED = 'SET_PROJECT_SAVE_AS_INITIATED';
export const SET_PROJECT_LAST_SAVED_DATE = 'SET_PROJECT_LAST_SAVED_DATE';
export const SET_PROJECT_ID = 'SET_PROJECT_ID';
export const SET_PROJECTS_OPEN_INITIATED = 'SET_PROJECTS_OPEN_INITIATED';
export const SET_PROJECT_NAME = 'SET_PROJECT_NAME';
export const SET_PROJECT_NAME_EDITING_INITIATED = 'SET_PROJECT_NAME_EDITING_INITIATED';
export const RESET_PROJECT_NAME_EDITING_INITIATED = 'RESET_PROJECT_NAME_EDITING_INITIATED';
export const SET_FILE_UPLOAD_PERCENTAGE = 'SET_FILE_UPLOAD_PERCENTAGE';
export const SET_FILE_UPLOAD_FAILED = 'SET_FILE_UPLOAD_FAILED';
export const SET_PROJECT_DELETE_INITIATED = 'SET_PROJECT_DELETE_INITIATED';
export const RESET_PROJECT_DELETE_INITIATED = 'RESET_PROJECT_DELETE_INITIATED';
export const SET_PROJECT_DELETE_FAILED = 'SET_PROJECT_DELETE_FAILED';
export const RESET_PROJECT_DELETE_FAILED = 'RESET_PROJECT_DELETE_FAILED';
export const SET_GET_PROJECT_FILES_FAILED = 'SET_GET_PROJECT_FILES_FAILED';
export const RESET_GET_PROJECT_FILES_FAILED = 'RESET_GET_PROJECT_FILES_FAILED';
export const SET_MODEL_FIT_FAILED = 'SET_MODEL_FIT_FAILED';
export const RESET_MODEL_FIT_FAILED = 'RESET_MODEL_FIT_FAILED';

// ProjectsActions
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_PROJECTS_FAILED = 'SET_PROJECTS_FAILED';

// ToastActions
export const DISPLAY_TOAST = 'DISPLAY_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';
export const SET_TOAST_TEXT = 'SET_TOAST_TEXT';
